### ISSUE TITLE
Noninteractive mode

### ISSUE THREAD

**Issue by ghost** [ThomasLeister/mastopurge#17]
It'd be great if mastopurge could be run non-interactively, e.g. through a cron job. Either the max duration could be saved in the config file or provided through a command-line flag.

**Comment by brortao** [comment]
i implemented this for myself in a fork: https://github.com/brortao/mastopurge/commit/63edf24c2b67dd049c0388280e5c06d5d3feb69e

note that it doesn't work if you set it to delete all posts (i.e. max_age_hours = 0). not sure how to get around that neatly since i've never worked with go before, but let me know if you'd like me to open a PR with this.

**Comment by mig5** [comment]
In the meantime, `echo "30 days" | mastopurge` seems to work just fine :)

**Comment by ThomasLeister** [comment]
Feature was introduced in version 1.2.0 :) (fixed via https://github.com/ThomasLeister/mastopurge/commit/7646af239f62d325bfb2df91c7d262a9f703e579 )
